In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('/content/drive/MyDrive/프로젝트/DART/2021_01_사업보고서 재무상태표.csv', encoding='cp949')

In [9]:
df

,재무제표종류,종목코드,회사명,시장구분,업종,업종명,결산월,결산기준일,보고서종류,통화,항목코드,항목명,당기,전기,전전기
0,재무상태표. 유동/비유동법-별도재무제표,[060310],3S,코스닥시장상장법인,292,특수 목적용 기계 제조업,3,2021-03-31,사업보고서,KRW,ifrs-full_AssetsAbstract,자산 [abstract],NaN,NaN,NaN
1,재무상태표. 유동/비유동법-별도재무제표,[060310],3S,코스닥시장상장법인,292,특수 목적용 기계 제조업,3,2021-03-31,사업보고서,KRW,ifrs-full_CurrentAssets,유동자산,"16,020,752,276","18,023,023,716","16,139,731,967"
2,재무상태표. 유동/비유동법-별도재무제표,[060310],3S,코스닥시장상장법인,292,특수 목적용 기계 제조업,3,2021-03-31,사업보고서,KRW,ifrs-full_CashAndCashEquivalents,현금및현금성자산,"5,202,901,349","5,391,980,645","6,709,567,383"
3,재무상태표. 유동/비유동법-별도재무제표,[060310],3S,코스닥시장상장법인,292,특수 목적용 기계 제조업,3,2021-03-31,사업보고서,KRW,dart_ShortTermDepositsNotClassifiedAsCashEquiv...,단기금융상품,NaN,"62,342,000","58,024,050"
4,재무상태표. 유동/비유동법-별도재무제표,[060310],3S,코스닥시장상장법인,292,특수 목적용 기계 제조업,3,2021-03-31,사업보고서,KRW,ifrs-full_TradeAndOtherCurrentReceivables,매출채권 및 기타채권,"4,332,907,324","3,571,617,812","5,259,536,143"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99267,재무상태표. 유동/비유동법-별도재무제표,[238490],힘스,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-12-31,사업보고서,KRW,dart_CapitalSurplus,자본잉여금,"18,343,640,240","18,979,117,110","21,742,145,246"
99268,재무상태표. 유동/비유동법-별도재무제표,[238490],힘스,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-12-31,사업보고서,KRW,dart_ElementsOfOtherStockholdersEquity,기타자본구성요소,"-2,058,802,350","-1,006,918,397","-1,824,163,644"
99269,재무상태표. 유동/비유동법-별도재무제표,[238490],힘스,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-12-31,사업보고서,KRW,ifrs-full_RetainedEarnings,이익잉여금(결손금),"51,975,278,965","54,113,506,801","38,028,975,327"
99270,재무상태표. 유동/비유동법-별도재무제표,[238490],힘스,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-12-31,사업보고서,KRW,ifrs-full_Equity,자본총계,"73,916,234,855","77,741,823,514","60,775,015,929"
99271,재무상태표. 유동/비유동법-별도재무제표,[238490],힘스,코스닥시장상장법인,292,특수 목적용 기계 제조업,12,2021-12-31,사업보고서,KRW,ifrs-full_EquityAndLiabilities,자본과부채총계,"84,293,187,571","90,835,511,525","86,740,548,269"

In [10]:
df.columns

Index(['재무제표종류', '종목코드', '회사명', '시장구분', '업종', '업종명', '결산월', '결산기준일', '보고서종류',
       '통화', '항목코드', '항목명', ' 당기 ', ' 전기 ', ' 전전기 '],
      dtype='object')

In [11]:
df.head()

,재무제표종류,종목코드,회사명,시장구분,업종,업종명,결산월,결산기준일,보고서종류,통화,항목코드,항목명,당기,전기,전전기
0,재무상태표. 유동/비유동법-별도재무제표,[060310],3S,코스닥시장상장법인,292,특수 목적용 기계 제조업,3,2021-03-31,사업보고서,KRW,ifrs-full_AssetsAbstract,자산 [abstract],NaN,NaN,NaN
1,재무상태표. 유동/비유동법-별도재무제표,[060310],3S,코스닥시장상장법인,292,특수 목적용 기계 제조업,3,2021-03-31,사업보고서,KRW,ifrs-full_CurrentAssets,유동자산,"16,020,752,276","18,023,023,716","16,139,731,967"
2,재무상태표. 유동/비유동법-별도재무제표,[060310],3S,코스닥시장상장법인,292,특수 목적용 기계 제조업,3,2021-03-31,사업보고서,KRW,ifrs-full_CashAndCashEquivalents,현금및현금성자산,"5,202,901,349","5,391,980,645","6,709,567,383"
3,재무상태표. 유동/비유동법-별도재무제표,[060310],3S,코스닥시장상장법인,292,특수 목적용 기계 제조업,3,2021-03-31,사업보고서,KRW,dart_ShortTermDepositsNotClassifiedAsCashEquiv...,단기금융상품,NaN,"62,342,000","58,024,050"
4,재무상태표. 유동/비유동법-별도재무제표,[060310],3S,코스닥시장상장법인,292,특수 목적용 기계 제조업,3,2021-03-31,사업보고서,KRW,ifrs-full_TradeAndOtherCurrentReceivables,매출채권 및 기타채권,"4,332,907,324","3,571,617,812","5,259,536,143"

## 유동자산
- 항목코드 : ifrs-full_CurrentAssets
- 변수계산 : 유동비율

In [16]:
#유동자산 행만 추출
df_1 = df[(df['항목코드']=='ifrs-full_CurrentAssets')|(df['항목명']=='   유동자산')]


#유동자산 열이름 바꾸기
df_1.columns = ['재무제표종류', '종목코드', '회사명', '시장구분', '업종', '업종명', '결산월', '결산기준일', '보고서종류',
       '통화', '항목코드', '항목명', '유동자산_당기', '유동자산_전기', '유동자산_전전기']


#불필요한 열 제거
df_1 = df_1[['회사명', '유동자산_당기', '유동자산_전기', '유동자산_전전기']]

In [17]:
df_1

          회사명            유동자산_당기            유동자산_전기           유동자산_전전기
1          3S    16,020,752,276     18,023,023,716     16,139,731,967
41     AJ네트웍스   130,457,258,750    156,297,229,968    273,884,243,596
92      AK홀딩스     4,424,324,709     11,433,465,226      6,195,148,908
124    APS홀딩스    60,721,860,931     15,995,084,893     33,462,621,949
180     AP시스템   286,554,851,999    218,022,676,161    249,272,776,666
...       ...                ...                ...                ...
99050      흥국    49,576,813,532     39,694,453,017     31,577,505,173
99091  흥국에프엔비    41,619,766,190     38,374,409,491     37,139,401,971
99132    흥아해운    53,674,943,319     51,275,585,950     61,182,849,921
99171      희림   126,972,900,121    121,079,203,016    122,067,338,371
99218      힘스    33,613,521,761     48,267,546,605     48,590,563,187

[2236 rows x 4 columns]

## 유동부채
- 항목코드 : ifrs-full_CurrentLiabilities
- 변수계산 : 유동비율

In [18]:
#유동부채 행만 추출
df_2 = df[(df['항목코드']=='ifrs-full_CurrentLiabilities')|(df['항목명']=='   유동부채')]


#유동부채 열이름 바꾸기
df_2.columns = ['재무제표종류', '종목코드', '회사명', '시장구분', '업종', '업종명', '결산월', '결산기준일', '보고서종류',
       '통화', '항목코드', '항목명', '유동부채_당기', '유동부채_전기', '유동부채_전전기']


#불필요한 열 제거
df_2 = df_2[['회사명', '유동부채_당기', '유동부채_전기', '유동부채_전전기']]

In [19]:
df_2

          회사명            유동부채_당기            유동부채_전기           유동부채_전전기
21         3S    14,676,537,890     13,097,592,540     16,273,940,263
66     AJ네트웍스   397,997,623,454    491,937,779,549    515,304,974,244
106     AK홀딩스   216,506,590,361    151,234,427,824     93,390,213,847
150    APS홀딩스    39,248,529,244     12,118,180,694      7,673,192,799
203     AP시스템   135,131,879,162    152,317,933,052    285,970,844,793
...       ...                ...                ...                ...
99067      흥국    15,936,730,823     18,652,272,884     15,237,980,421
99109  흥국에프엔비    44,198,116,580     22,901,200,158     24,401,481,690
99152    흥아해운    26,798,507,662    146,027,932,498    178,068,105,912
99192      희림    94,884,552,607     92,867,448,498     96,015,456,264
99245      힘스     8,553,693,388     11,014,966,808     22,705,592,894

[2236 rows x 4 columns]

## 자본총계(자기자본)
- 항목코드 : ifrs-full_Equity
- 변수계산 : 부채비율의 자기자본, 자기자본순이익률의 자기자본

In [20]:
#자본총계 행만 추출
df_3 = df[(df['항목코드']=='ifrs-full_Equity')|(df['항목명']=='   자본총계')]


#자본총계 열이름 바꾸기
df_3.columns = ['재무제표종류', '종목코드', '회사명', '시장구분', '업종', '업종명', '결산월', '결산기준일', '보고서종류',
       '통화', '항목코드', '항목명', '자본총계(자기자본)_당기', '자본총계(자기자본)_전기', '자본총계(자기자본)_전전기']


#불필요한 열 제거
df_3 = df_3[['회사명', '자본총계(자기자본)_당기', '자본총계(자기자본)_전기', '자본총계(자기자본)_전전기']]

In [21]:
df_3

          회사명      자본총계(자기자본)_당기      자본총계(자기자본)_전기     자본총계(자기자본)_전전기
38         3S    34,906,851,552     32,382,338,493     33,053,418,334
89     AJ네트웍스   372,788,339,851    298,444,706,674    310,448,638,891
121     AK홀딩스   537,304,001,226    516,710,196,269    517,879,021,747
177    APS홀딩스   186,810,490,637    165,530,734,817    209,969,587,090
228     AP시스템   189,072,456,030    136,563,465,651    113,375,745,767
...       ...                ...                ...                ...
99088      흥국    70,357,355,889     57,442,608,119     54,944,603,779
99129  흥국에프엔비    76,497,918,931     67,613,965,481     62,661,707,914
99168    흥아해운   108,146,996,426    -20,161,176,456     17,632,229,055
99215      희림    60,611,903,169     57,246,914,998     54,016,890,219
99270      힘스    73,916,234,855     77,741,823,514     60,775,015,929

[2230 rows x 4 columns]

## 부채총계(총부채)
- 항목코드 : ifrs-full_Liabilities
- 변수계산 : 부채비율의 총부채

In [22]:
#부채총계 행만 추출
df_4 = df[(df['항목코드']=='ifrs-full_Liabilities')|(df['항목명']=='   부채총계')]


#부채총계 열이름 바꾸기
df_4.columns = ['재무제표종류', '종목코드', '회사명', '시장구분', '업종', '업종명', '결산월', '결산기준일', '보고서종류',
       '통화', '항목코드', '항목명', '부채총계(총부채)_당기', '부채총계(총부채)_전기', '부채총계(총부채)_전전기']


#불필요한 열 제거
df_4 = df_4[['회사명', '부채총계(총부채)_당기', '부채총계(총부채)_전기', '부채총계(총부채)_전전기']]

In [23]:
df_4

          회사명       부채총계(총부채)_당기       부채총계(총부채)_전기      부채총계(총부채)_전전기
33         3S    16,924,341,659     15,870,976,209     18,010,061,233
81     AJ네트웍스   825,420,971,795    905,693,248,015    921,116,846,324
115     AK홀딩스   231,709,514,056    157,781,350,001     93,652,273,828
167    APS홀딩스    84,672,371,378     23,689,474,456     32,124,646,644
221     AP시스템   236,708,995,844    232,217,362,799    305,989,882,799
...       ...                ...                ...                ...
99082      흥국    19,770,057,673     21,449,050,975     18,289,762,520
99123  흥국에프엔비    46,173,240,885     24,224,277,760     25,545,697,192
99162    흥아해운   139,842,915,756    304,928,523,008    368,918,610,066
99208      희림   111,182,590,943    108,183,083,443    106,190,260,337
99264      힘스    10,376,952,716     13,093,688,011     25,965,532,340

[2237 rows x 4 columns]

## 자산총계
- 항목코드 : ifrs-full_Assets
- 변수계산 : 총자산증가율(총자산)

In [24]:
#자산총계 행만 추출
df_5 = df[(df['항목코드']=='ifrs-full_Assets')|(df['항목명']=='   자산총계')]


#자산총계 열이름 바꾸기
df_5.columns = ['재무제표종류', '종목코드', '회사명', '시장구분', '업종', '업종명', '결산월', '결산기준일', '보고서종류',
       '통화', '항목코드', '항목명', '자산총계_당기', '자산총계_전기', '자산총계_전전기']


#불필요한 열 제거
df_5 = df_5[['회사명', '자산총계_당기', '자산총계_전기', '자산총계_전전기']]

In [25]:
df_5

          회사명              자산총계_당기              자산총계_전기             자산총계_전전기
19         3S      51,831,193,211       48,253,314,702       51,063,479,567
64     AJ네트웍스   1,198,209,311,646    1,204,137,954,689    1,231,565,485,215
104     AK홀딩스     769,013,515,282      674,491,546,270      611,531,295,575
148    APS홀딩스     271,482,862,015      189,220,209,273      242,094,233,734
201     AP시스템     425,781,451,874      368,780,828,450      419,365,628,566
...       ...                  ...                  ...                  ...
99065      흥국      90,127,413,562       78,891,659,094       73,234,366,299
99107  흥국에프엔비     122,671,159,816       91,838,243,241       88,207,405,106
99150    흥아해운     247,989,912,182      284,767,346,552      386,550,839,121
99190      희림     171,794,494,112      165,429,998,441      160,207,150,556
99243      힘스      84,293,187,571       90,835,511,525       86,740,548,269

[2236 rows x 4 columns]

------

# 파일 합치기

In [26]:
p = pd.merge(df_1, df_2, how='outer', on='회사명')

In [28]:
p

,회사명,유동자산_당기,유동자산_전기,유동자산_전전기,유동부채_당기,유동부채_전기,유동부채_전전기
0,3S,"16,020,752,276","18,023,023,716","16,139,731,967","14,676,537,890","13,097,592,540","16,273,940,263"
1,AJ네트웍스,"130,457,258,750","156,297,229,968","273,884,243,596","397,997,623,454","491,937,779,549","515,304,974,244"
2,AK홀딩스,"4,424,324,709","11,433,465,226","6,195,148,908","216,506,590,361","151,234,427,824","93,390,213,847"
3,APS홀딩스,"60,721,860,931","15,995,084,893","33,462,621,949","39,248,529,244","12,118,180,694","7,673,192,799"
4,AP시스템,"286,554,851,999","218,022,676,161","249,272,776,666","135,131,879,162","152,317,933,052","285,970,844,793"
...,...,...,...,...,...,...,...
2255,흥국,"49,576,813,532","39,694,453,017","31,577,505,173","15,936,730,823","18,652,272,884","15,237,980,421"
2256,흥국에프엔비,"41,619,766,190","38,374,409,491","37,139,401,971","44,198,116,580","22,901,200,158","24,401,481,690"
2257,흥아해운,"53,674,943,319","51,275,585,950","61,182,849,921","26,798,507,662","146,027,932,498","178,068,105,912"
2258,희림,"126,972,900,121","121,079,203,016","122,067,338,371","94,884,552,607","92,867,448,498","96,015,456,264"
2259,힘스,"33,613,521,761","48,267,546,605","48,590,563,187","8,553,693,388","11,014,966,808","22,705,592,894"

In [29]:
p2 = pd.merge(p, df_3, how='outer', on='회사명')

In [30]:
p2

,회사명,유동자산_당기,유동자산_전기,유동자산_전전기,유동부채_당기,유동부채_전기,유동부채_전전기,자본총계(자기자본)_당기,자본총계(자기자본)_전기,자본총계(자기자본)_전전기
0,3S,"16,020,752,276","18,023,023,716","16,139,731,967","14,676,537,890","13,097,592,540","16,273,940,263","34,906,851,552","32,382,338,493","33,053,418,334"
1,AJ네트웍스,"130,457,258,750","156,297,229,968","273,884,243,596","397,997,623,454","491,937,779,549","515,304,974,244","372,788,339,851","298,444,706,674","310,448,638,891"
2,AK홀딩스,"4,424,324,709","11,433,465,226","6,195,148,908","216,506,590,361","151,234,427,824","93,390,213,847","537,304,001,226","516,710,196,269","517,879,021,747"
3,APS홀딩스,"60,721,860,931","15,995,084,893","33,462,621,949","39,248,529,244","12,118,180,694","7,673,192,799","186,810,490,637","165,530,734,817","209,969,587,090"
4,AP시스템,"286,554,851,999","218,022,676,161","249,272,776,666","135,131,879,162","152,317,933,052","285,970,844,793","189,072,456,030","136,563,465,651","113,375,745,767"
...,...,...,...,...,...,...,...,...,...,...
2304,흥국에프엔비,"41,619,766,190","38,374,409,491","37,139,401,971","44,198,116,580","22,901,200,158","24,401,481,690","76,497,918,931","67,613,965,481","62,661,707,914"
2305,흥아해운,"53,674,943,319","51,275,585,950","61,182,849,921","26,798,507,662","146,027,932,498","178,068,105,912","108,146,996,426","-20,161,176,456","17,632,229,055"
2306,희림,"126,972,900,121","121,079,203,016","122,067,338,371","94,884,552,607","92,867,448,498","96,015,456,264","60,611,903,169","57,246,914,998","54,016,890,219"
2307,힘스,"33,613,521,761","48,267,546,605","48,590,563,187","8,553,693,388","11,014,966,808","22,705,592,894","73,916,234,855","77,741,823,514","60,775,015,929"
2308,CNH,NaN,NaN,NaN,NaN,NaN,NaN,"113,308,407,219","125,576,039,518","98,396,218,343"

In [31]:
p3 = pd.merge(p2, df_4, how='outer', on='회사명')

In [32]:
p3

,회사명,유동자산_당기,유동자산_전기,유동자산_전전기,유동부채_당기,유동부채_전기,유동부채_전전기,자본총계(자기자본)_당기,자본총계(자기자본)_전기,자본총계(자기자본)_전전기,부채총계(총부채)_당기,부채총계(총부채)_전기,부채총계(총부채)_전전기
0,3S,"16,020,752,276","18,023,023,716","16,139,731,967","14,676,537,890","13,097,592,540","16,273,940,263","34,906,851,552","32,382,338,493","33,053,418,334","16,924,341,659","15,870,976,209","18,010,061,233"
1,AJ네트웍스,"130,457,258,750","156,297,229,968","273,884,243,596","397,997,623,454","491,937,779,549","515,304,974,244","372,788,339,851","298,444,706,674","310,448,638,891","825,420,971,795","905,693,248,015","921,116,846,324"
2,AK홀딩스,"4,424,324,709","11,433,465,226","6,195,148,908","216,506,590,361","151,234,427,824","93,390,213,847","537,304,001,226","516,710,196,269","517,879,021,747","231,709,514,056","157,781,350,001","93,652,273,828"
3,APS홀딩스,"60,721,860,931","15,995,084,893","33,462,621,949","39,248,529,244","12,118,180,694","7,673,192,799","186,810,490,637","165,530,734,817","209,969,587,090","84,672,371,378","23,689,474,456","32,124,646,644"
4,AP시스템,"286,554,851,999","218,022,676,161","249,272,776,666","135,131,879,162","152,317,933,052","285,970,844,793","189,072,456,030","136,563,465,651","113,375,745,767","236,708,995,844","232,217,362,799","305,989,882,799"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2400,흥국에프엔비,"41,619,766,190","38,374,409,491","37,139,401,971","44,198,116,580","22,901,200,158","24,401,481,690","76,497,918,931","67,613,965,481","62,661,707,914","46,173,240,885","24,224,277,760","25,545,697,192"
2401,흥아해운,"53,674,943,319","51,275,585,950","61,182,849,921","26,798,507,662","146,027,932,498","178,068,105,912","108,146,996,426","-20,161,176,456","17,632,229,055","139,842,915,756","304,928,523,008","368,918,610,066"
2402,희림,"126,972,900,121","121,079,203,016","122,067,338,371","94,884,552,607","92,867,448,498","96,015,456,264","60,611,903,169","57,246,914,998","54,016,890,219","111,182,590,943","108,183,083,443","106,190,260,337"
2403,힘스,"33,613,521,761","48,267,546,605","48,590,563,187","8,553,693,388","11,014,966,808","22,705,592,894","73,916,234,855","77,741,823,514","60,775,015,929","10,376,952,716","13,093,688,011","25,965,532,340"
2404,CNH,NaN,NaN,NaN,NaN,NaN,NaN,"113,308,407,219","125,576,039,518","98,396,218,343","45,361,817,273","45,920,116,585","43,207,088,205"

In [35]:
fi = pd.merge(p3, df_5, how='outer', on='회사명')

In [36]:
fi

,회사명,유동자산_당기,유동자산_전기,유동자산_전전기,유동부채_당기,유동부채_전기,유동부채_전전기,자본총계(자기자본)_당기,자본총계(자기자본)_전기,자본총계(자기자본)_전전기,부채총계(총부채)_당기,부채총계(총부채)_전기,부채총계(총부채)_전전기,자산총계_당기,자산총계_전기,자산총계_전전기
0,3S,"16,020,752,276","18,023,023,716","16,139,731,967","14,676,537,890","13,097,592,540","16,273,940,263","34,906,851,552","32,382,338,493","33,053,418,334","16,924,341,659","15,870,976,209","18,010,061,233","51,831,193,211","48,253,314,702","51,063,479,567"
1,AJ네트웍스,"130,457,258,750","156,297,229,968","273,884,243,596","397,997,623,454","491,937,779,549","515,304,974,244","372,788,339,851","298,444,706,674","310,448,638,891","825,420,971,795","905,693,248,015","921,116,846,324","1,198,209,311,646","1,204,137,954,689","1,231,565,485,215"
2,AK홀딩스,"4,424,324,709","11,433,465,226","6,195,148,908","216,506,590,361","151,234,427,824","93,390,213,847","537,304,001,226","516,710,196,269","517,879,021,747","231,709,514,056","157,781,350,001","93,652,273,828","769,013,515,282","674,491,546,270","611,531,295,575"
3,APS홀딩스,"60,721,860,931","15,995,084,893","33,462,621,949","39,248,529,244","12,118,180,694","7,673,192,799","186,810,490,637","165,530,734,817","209,969,587,090","84,672,371,378","23,689,474,456","32,124,646,644","271,482,862,015","189,220,209,273","242,094,233,734"
4,AP시스템,"286,554,851,999","218,022,676,161","249,272,776,666","135,131,879,162","152,317,933,052","285,970,844,793","189,072,456,030","136,563,465,651","113,375,745,767","236,708,995,844","232,217,362,799","305,989,882,799","425,781,451,874","368,780,828,450","419,365,628,566"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2592,흥국에프엔비,"41,619,766,190","38,374,409,491","37,139,401,971","44,198,116,580","22,901,200,158","24,401,481,690","76,497,918,931","67,613,965,481","62,661,707,914","46,173,240,885","24,224,277,760","25,545,697,192","122,671,159,816","91,838,243,241","88,207,405,106"
2593,흥아해운,"53,674,943,319","51,275,585,950","61,182,849,921","26,798,507,662","146,027,932,498","178,068,105,912","108,146,996,426","-20,161,176,456","17,632,229,055","139,842,915,756","304,928,523,008","368,918,610,066","247,989,912,182","284,767,346,552","386,550,839,121"
2594,희림,"126,972,900,121","121,079,203,016","122,067,338,371","94,884,552,607","92,867,448,498","96,015,456,264","60,611,903,169","57,246,914,998","54,016,890,219","111,182,590,943","108,183,083,443","106,190,260,337","171,794,494,112","165,429,998,441","160,207,150,556"
2595,힘스,"33,613,521,761","48,267,546,605","48,590,563,187","8,553,693,388","11,014,966,808","22,705,592,894","73,916,234,855","77,741,823,514","60,775,015,929","10,376,952,716","13,093,688,011","25,965,532,340","84,293,187,571","90,835,511,525","86,740,548,269"
2596,CNH,NaN,NaN,NaN,NaN,NaN,NaN,"113,308,407,219","125,576,039,518","98,396,218,343","45,361,817,273","45,920,116,585","43,207,088,205","158,670,224,492","171,496,156,103","141,603,306,548"

In [37]:
#파일저장
fi.to_csv('재무상태표 변수추출.csv', encoding='utf-8-sig')