In [6]:
import pandas as pd

df = pd.read_csv("./20202021data.csv", encoding = "euc-kr")

In [8]:
df.columns

Index(['Unnamed: 0', '회사명', '상장유지년도_2020(X1)', '2020 배당성향(X3)', '2020 배당률(X4)',
       '당기순손실여부_2020(X5)', '주당순이익감소여부_2020(X6)', '유동비율_전기(X7)', '부채비율_전기(X8)',
       '총자산증가율_전기(X10)', '매출액증가율_전기(X11)', '매출액순이익률_전기(X12)',
       '총자본영업이익률_전기(X13)', '자기자본순이익률_전기(X14)', '2020_외국인지분율(X17)',
       '외국인지분율변동_2020(X18)', '배당정책_2020(Y)'],
      dtype='object')

In [9]:
df = df[[ '회사명', '상장유지년도_2020(X1)', '2020 배당성향(X3)', '2020 배당률(X4)',
       '당기순손실여부_2020(X5)', '주당순이익감소여부_2020(X6)', '유동비율_전기(X7)', '부채비율_전기(X8)',
       '총자산증가율_전기(X10)', '매출액증가율_전기(X11)', '매출액순이익률_전기(X12)',
       '총자본영업이익률_전기(X13)', '자기자본순이익률_전기(X14)', '2020_외국인지분율(X17)',
       '외국인지분율변동_2020(X18)', '배당정책_2020(Y)']]

In [13]:
df.columns = ['회사명','상장유지년도(X1)', '배당성향(X3)', '배당률(X4)',
       '당기순손실여부(X5)', '주당순이익감소여부(X6)', '유동비율(X7)', '부채비율(X8)',
       '총자산증가율(X10)', '매출액증가율(X11)', '매출액순이익률(X12)',
       '총자본영업이익률(X13)', '자기자본순이익률(X14)', '외국인지분율(X17)',
       '외국인지분율변동(X18)', '배당정책(Y)']

In [14]:
df.head()

,회사명,상장유지년도(X1),배당성향(X3),배당률(X4),당기순손실여부(X5),주당순이익감소여부(X6),유동비율(X7),부채비율(X8),총자산증가율(X10),매출액증가율(X11),매출액순이익률(X12),총자본영업이익률(X13),자기자본순이익률(X14),외국인지분율(X17),외국인지분율변동(X18),배당정책(Y)
0,AJ네트웍스,6,296.433,21.0,0,1,31.77,303.47,-2.23,15.77,3.77,4.18,5.74,10.75,0,0
1,AK홀딩스,22,1.963,8.0,0,1,7.56,30.54,10.30,34.22,20.66,4.69,1.82,8.39,1,0
2,AP시스템,4,8.452,24.0,0,0,143.14,170.04,-12.06,26.74,4.11,12.24,17.57,10.70,1,1
3,BGF,7,58.878,11.0,0,0,4111.19,2.73,0.89,44.54,43.02,2.12,1.52,8.18,1,0
4,BGF리테일,4,33.787,240.0,0,1,82.03,243.77,9.18,3.78,2.04,7.09,18.75,30.82,1,0

In [16]:
년도 = []
for i in range(664):
    if i < 332:
        년도.append(2020)
    else:
        년도.append(2021)

In [18]:
df['년도'] = 년도

In [19]:
df.head()

,회사명,상장유지년도(X1),배당성향(X3),배당률(X4),당기순손실여부(X5),주당순이익감소여부(X6),유동비율(X7),부채비율(X8),총자산증가율(X10),매출액증가율(X11),매출액순이익률(X12),총자본영업이익률(X13),자기자본순이익률(X14),외국인지분율(X17),외국인지분율변동(X18),배당정책(Y),년도
0,AJ네트웍스,6,296.433,21.0,0,1,31.77,303.47,-2.23,15.77,3.77,4.18,5.74,10.75,0,0,2020
1,AK홀딩스,22,1.963,8.0,0,1,7.56,30.54,10.30,34.22,20.66,4.69,1.82,8.39,1,0,2020
2,AP시스템,4,8.452,24.0,0,0,143.14,170.04,-12.06,26.74,4.11,12.24,17.57,10.70,1,1,2020
3,BGF,7,58.878,11.0,0,0,4111.19,2.73,0.89,44.54,43.02,2.12,1.52,8.18,1,0,2020
4,BGF리테일,4,33.787,240.0,0,1,82.03,243.77,9.18,3.78,2.04,7.09,18.75,30.82,1,0,2020

In [29]:
df.sort_values('매출액증가율(X11)', ascending = False)[['회사명', '매출액증가율(X11)',  '배당정책(Y)','년도']].head(10)

          회사명  매출액증가율(X11)  배당정책(Y)    년도
380    SGC에너지       565.53        0  2021
232    멕아이씨에스       561.30        1  2020
32     KPX홀딩스       470.06        1  2020
37    LS전선아시아       287.35        1  2020
532    디스플레이텍       239.06        0  2021
199   디바이스이엔지       191.88        1  2020
60     SNT홀딩스       129.76        1  2020
142     대성홀딩스       117.63        0  2020
86   골프존뉴딘홀딩스       113.75        0  2020
243     바디텍메드       106.56        1  2020

In [32]:
df.sort_values('자기자본순이익률(X14)', ascending = False)[['회사명', '자기자본순이익률(X14)',  '배당정책(Y)','년도']].head(10)

          회사명  자기자본순이익률(X14)  배당정책(Y)    년도
49   SGC이테크건설         105.81        0  2020
232    멕아이씨에스          60.29        1  2020
542  디티알오토모티브          48.02        0  2021
277     삼성출판사          46.19        1  2020
321     성도이엔지          39.30        1  2020
201       디알젬          37.39        1  2020
243     바디텍메드          37.25        1  2020
80     고려신용정보          34.44        1  2020
199   디바이스이엔지          30.76        1  2020
334     AP시스템          29.99        1  2021

In [33]:
df.sort_values('총자산증가율(X10)', ascending = False)[['회사명', '총자산증가율(X10)',  '배당정책(Y)','년도']].head(10)

          회사명  총자산증가율(X10)  배당정책(Y)    년도
542  디티알오토모티브       243.07        0  2021
232    멕아이씨에스       200.56        1  2020
277     삼성출판사        94.06        1  2020
539     디지털대성        90.98        1  2021
348     HDC랩스        89.02        1  2021
639     서린바이오        78.65        0  2021
127   뉴파워프라즈마        71.05        1  2020
243     바디텍메드        60.22        1  2020
423      국도화학        57.72        1  2021
166      덕우전자        48.73        0  2020

In [34]:
df.sort_values('배당률(X4)', ascending = False)[['회사명', '배당률(X4)',  '배당정책(Y)','년도']].head(10)

         회사명  배당률(X4)  배당정책(Y)    년도
608     삼성물산   4200.0        1  2021
384       SK   4000.0        1  2021
52        SK   3500.0        1  2020
276     삼성물산   2300.0        1  2020
561  메가스터디교육   2000.0        1  2021
572     미원상사   1200.0        1  2021
117      넷마블    767.0        1  2020
229  메가스터디교육    750.0        0  2020
552     롯데지주    750.0        1  2021
417      골프존    700.0        1  2021

In [35]:
df.sort_values('총자본영업이익률(X13)', ascending = False)[['회사명', '총자본영업이익률(X13)',  '배당정책(Y)','년도']].head(10)

         회사명  총자본영업이익률(X13)  배당정책(Y)    년도
232   멕아이씨에스          44.38        1  2020
243    바디텍메드          40.06        1  2020
201      디알젬          31.25        1  2020
199  디바이스이엔지          27.75        1  2020
575    바디텍메드          27.36        0  2021
555     리노공업          25.11        1  2021
417      골프존          23.29        1  2021
614    삼양옵틱스          23.10        1  2021
573    미원에스씨          23.10        1  2021
126      뉴트리          22.25        1  2020